/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.util.ArrayList;
import modelo.Chave;


/**
 *
 * @author IFPR
 */
public class TelaPrincipal extends javax.swing.JFrame {
    ArrayList<Chave> todasChaves = new ArrayList<>() ;
    
    public TelaPrincipal() {       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMPessoa = new javax.swing.JMenu();
        jMVigilante = new javax.swing.JMenu();
        jMICadastrarVigilante = new javax.swing.JMenuItem();
        jMIPesquisarVigilante = new javax.swing.JMenuItem();
        jMIAlterarVigilante = new javax.swing.JMenuItem();
        jMIExcluirVigilante = new javax.swing.JMenuItem();
        jMServidor = new javax.swing.JMenu();
        jMICadastarServidor = new javax.swing.JMenuItem();
        jMIPesquisarSevidor = new javax.swing.JMenuItem();
        jMIAlterarServidor = new javax.swing.JMenuItem();
        jMIExcluirServidor = new javax.swing.JMenuItem();
        jMEstudante = new javax.swing.JMenu();
        jMICadastrarEstudante = new javax.swing.JMenuItem();
        jMIPesquisarEstudante = new javax.swing.JMenuItem();
        jMIAlterarEstudante = new javax.swing.JMenuItem();
        jMIExcluirEstudante = new javax.swing.JMenuItem();
        jMChave = new javax.swing.JMenu();
        jMICadastarChave = new javax.swing.JMenuItem();
        jMIPesquisarChave = new javax.swing.JMenuItem();
        jMIAlterarChave = new javax.swing.JMenuItem();
        jMIExcluirChave = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Carlos Eduardo Teixeira de Souza");

        jLabel2.setBackground(new java.awt.Color(51, 51, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Turma:IIN2017");
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(0, 51, 255));
        jLabel3.setOpaque(true);

        jMPessoa.setText("Pessoa");

        jMVigilante.setText("Vigilante ");

        jMICadastrarVigilante.setText("Cadastrar Vigilante ");
        jMICadastrarVigilante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadastrarVigilanteActionPerformed(evt);
            }
        });
        jMVigilante.add(jMICadastrarVigilante);

        jMIPesquisarVigilante.setText("Pesquisar Vigilante ");
        jMIPesquisarVigilante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIPesquisarVigilanteActionPerformed(evt);
            }
        });
        jMVigilante.add(jMIPesquisarVigilante);

        jMIAlterarVigilante.setText("Alterar Vigilante");
        jMIAlterarVigilante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAlterarVigilanteActionPerformed(evt);
            }
        });
        jMVigilante.add(jMIAlterarVigilante);

        jMIExcluirVigilante.setText("Excluir Vigilante ");
        jMIExcluirVigilante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIExcluirVigilanteActionPerformed(evt);
            }
        });
        jMVigilante.add(jMIExcluirVigilante);

        jMPessoa.add(jMVigilante);

        jMServidor.setText("Servidor");

        jMICadastarServidor.setText("Cadastrar Servidor ");
        jMICadastarServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadastarServidorActionPerformed(evt);
            }
        });
        jMServidor.add(jMICadastarServidor);

        jMIPesquisarSevidor.setText("Pesquisar Servidor ");
        jMIPesquisarSevidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIPesquisarSevidorActionPerformed(evt);
            }
        });
        jMServidor.add(jMIPesquisarSevidor);

        jMIAlterarServidor.setText("Alterar Servidor ");
        jMIAlterarServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAlterarServidorActionPerformed(evt);
            }
        });
        jMServidor.add(jMIAlterarServidor);

        jMIExcluirServidor.setText("Excluir Servidor ");
        jMIExcluirServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIExcluirServidorActionPerformed(evt);
            }
        });
        jMServidor.add(jMIExcluirServidor);

        jMPessoa.add(jMServidor);

        jMEstudante.setText("Estudante ");

        jMICadastrarEstudante.setText("Cadastrar Estudante ");
        jMICadastrarEstudante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadastrarEstudanteActionPerformed(evt);
            }
        });
        jMEstudante.add(jMICadastrarEstudante);

        jMIPesquisarEstudante.setText("Pesquisar Estudante ");
        jMIPesquisarEstudante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIPesquisarEstudanteActionPerformed(evt);
            }
        });
        jMEstudante.add(jMIPesquisarEstudante);

        jMIAlterarEstudante.setText("Alterar Estudante ");
        jMIAlterarEstudante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAlterarEstudanteActionPerformed(evt);
            }
        });
        jMEstudante.add(jMIAlterarEstudante);

        jMIExcluirEstudante.setText("Excluir Estudante ");
        jMIExcluirEstudante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIExcluirEstudanteActionPerformed(evt);
            }
        });
        jMEstudante.add(jMIExcluirEstudante);

        jMPessoa.add(jMEstudante);

        jMenuBar2.add(jMPessoa);

        jMChave.setText("Chave");

        jMICadastarChave.setText("Cadastrar Chave ");
        jMICadastarChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICadastarChaveActionPerformed(evt);
            }
        });
        jMChave.add(jMICadastarChave);

        jMIPesquisarChave.setText("Pesquisar Chave");
        jMIPesquisarChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIPesquisarChaveActionPerformed(evt);
            }
        });
        jMChave.add(jMIPesquisarChave);

        jMIAlterarChave.setText("Alterar Chave ");
        jMIAlterarChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAlterarChaveActionPerformed(evt);
            }
        });
        jMChave.add(jMIAlterarChave);

        jMIExcluirChave.setText("Excluir Chave ");
        jMIExcluirChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIExcluirChaveActionPerformed(evt);
            }
        });
        jMChave.add(jMIExcluirChave);

        jMenuBar2.add(jMChave);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMICadastrarVigilanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadastrarVigilanteActionPerformed
      CadVigilante a = new CadVigilante();
      a.setVisible(true);
    }//GEN-LAST:event_jMICadastrarVigilanteActionPerformed

    private void jMIExcluirEstudanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIExcluirEstudanteActionPerformed
ExEstudante a = new ExEstudante();
a.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIExcluirEstudanteActionPerformed

    private void jMICadastarChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadastarChaveActionPerformed
        // TODO add your handling code here:
        CadChave a= new CadChave();
        a.setVisible(true);
    }//GEN-LAST:event_jMICadastarChaveActionPerformed

    private void jMIPesquisarChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIPesquisarChaveActionPerformed
       PesquisarChave b = new PesquisarChave();
       b.setVisible(true);
    }//GEN-LAST:event_jMIPesquisarChaveActionPerformed

    private void jMIAlterarChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAlterarChaveActionPerformed
    AltChave a = new AltChave();
    a.setVisible(true);
    }//GEN-LAST:event_jMIAlterarChaveActionPerformed

    private void jMIExcluirChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIExcluirChaveActionPerformed
     ExChave a = new ExChave();
     a.setVisible(true);
    }//GEN-LAST:event_jMIExcluirChaveActionPerformed

    private void jMIAlterarVigilanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAlterarVigilanteActionPerformed
    AltVigilante a =new AltVigilante();
    a.setVisible(true);
    }//GEN-LAST:event_jMIAlterarVigilanteActionPerformed

    private void jMIPesquisarVigilanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIPesquisarVigilanteActionPerformed
        // TODO add your handling code here:
        PesVigilante a =new PesVigilante();
        a.setVisible(true);
    }//GEN-LAST:event_jMIPesquisarVigilanteActionPerformed

    private void jMIExcluirVigilanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIExcluirVigilanteActionPerformed
        // TODO add your handling code here:
        ExVigilante a =new ExVigilante();
        a.setVisible(true);
    }//GEN-LAST:event_jMIExcluirVigilanteActionPerformed

    private void jMICadastarServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadastarServidorActionPerformed
        // TODO add your handling code here:
        CadServidor a=new CadServidor();
        a.setVisible(true);
    }//GEN-LAST:event_jMICadastarServidorActionPerformed

    private void jMIPesquisarSevidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIPesquisarSevidorActionPerformed
PesServidor a = new PesServidor();
a.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIPesquisarSevidorActionPerformed

    private void jMIAlterarServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAlterarServidorActionPerformed
AltServidor a = new AltServidor();
a.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIAlterarServidorActionPerformed

    private void jMIExcluirServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIExcluirServidorActionPerformed
ExServidor a =new ExServidor();
a.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIExcluirServidorActionPerformed

    private void jMICadastrarEstudanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICadastrarEstudanteActionPerformed
CadEStudante a =new CadEStudante();
a.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMICadastrarEstudanteActionPerformed

    private void jMIPesquisarEstudanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIPesquisarEstudanteActionPerformed
PesEstudante a=new PesEstudante();
a.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIPesquisarEstudanteActionPerformed

    private void jMIAlterarEstudanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAlterarEstudanteActionPerformed
     AltEstudante a =new AltEstudante();
     a.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMIAlterarEstudanteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMChave;
    private javax.swing.JMenu jMEstudante;
    private javax.swing.JMenuItem jMIAlterarChave;
    private javax.swing.JMenuItem jMIAlterarEstudante;
    private javax.swing.JMenuItem jMIAlterarServidor;
    private javax.swing.JMenuItem jMIAlterarVigilante;
    private javax.swing.JMenuItem jMICadastarChave;
    private javax.swing.JMenuItem jMICadastarServidor;
    private javax.swing.JMenuItem jMICadastrarEstudante;
    private javax.swing.JMenuItem jMICadastrarVigilante;
    private javax.swing.JMenuItem jMIExcluirChave;
    private javax.swing.JMenuItem jMIExcluirEstudante;
    private javax.swing.JMenuItem jMIExcluirServidor;
    private javax.swing.JMenuItem jMIExcluirVigilante;
    private javax.swing.JMenuItem jMIPesquisarChave;
    private javax.swing.JMenuItem jMIPesquisarEstudante;
    private javax.swing.JMenuItem jMIPesquisarSevidor;
    private javax.swing.JMenuItem jMIPesquisarVigilante;
    private javax.swing.JMenu jMPessoa;
    private javax.swing.JMenu jMServidor;
    private javax.swing.JMenu jMVigilante;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
